// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Glue.Outputs
{

    /// <summary>
    /// A column in a Table.
    /// </summary>
    [OutputType]
    public sealed class PartitionColumn
    {
        /// <summary>
        /// A free-form text comment.
        /// </summary>
        public readonly string? Comment;
        /// <summary>
        /// The name of the Column.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The data type of the Column.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private PartitionColumn(
            string? comment,

            string name,

            string? type)
        {
            Comment = comment;
            Name = name;
            Type = type;
        }
    }
}
