// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Kinesisfirehose.Outputs
{

    [OutputType]
    public sealed class DeliveryStreamElasticsearchDestinationConfiguration
    {
        public readonly Outputs.DeliveryStreamElasticsearchBufferingHints? BufferingHints;
        public readonly Outputs.DeliveryStreamCloudWatchLoggingOptions? CloudWatchLoggingOptions;
        public readonly string? ClusterEndpoint;
        public readonly string? DomainARN;
        public readonly string IndexName;
        public readonly string? IndexRotationPeriod;
        public readonly Outputs.DeliveryStreamProcessingConfiguration? ProcessingConfiguration;
        public readonly Outputs.DeliveryStreamElasticsearchRetryOptions? RetryOptions;
        public readonly string RoleARN;
        public readonly string? S3BackupMode;
        public readonly Outputs.DeliveryStreamS3DestinationConfiguration S3Configuration;
        public readonly string? TypeName;
        public readonly Outputs.DeliveryStreamVpcConfiguration? VpcConfiguration;

        [OutputConstructor]
        private DeliveryStreamElasticsearchDestinationConfiguration(
            Outputs.DeliveryStreamElasticsearchBufferingHints? bufferingHints,

            Outputs.DeliveryStreamCloudWatchLoggingOptions? cloudWatchLoggingOptions,

            string? clusterEndpoint,

            string? domainARN,

            string indexName,

            string? indexRotationPeriod,

            Outputs.DeliveryStreamProcessingConfiguration? processingConfiguration,

            Outputs.DeliveryStreamElasticsearchRetryOptions? retryOptions,

            string roleARN,

            string? s3BackupMode,

            Outputs.DeliveryStreamS3DestinationConfiguration s3Configuration,

            string? typeName,

            Outputs.DeliveryStreamVpcConfiguration? vpcConfiguration)
        {
            BufferingHints = bufferingHints;
            CloudWatchLoggingOptions = cloudWatchLoggingOptions;
            ClusterEndpoint = clusterEndpoint;
            DomainARN = domainARN;
            IndexName = indexName;
            IndexRotationPeriod = indexRotationPeriod;
            ProcessingConfiguration = processingConfiguration;
            RetryOptions = retryOptions;
            RoleARN = roleARN;
            S3BackupMode = s3BackupMode;
            S3Configuration = s3Configuration;
            TypeName = typeName;
            VpcConfiguration = vpcConfiguration;
        }
    }
}
