template: aws-native
provider: aws-native
major-version: 0
aws: true
providerDefaultBranch: master
checkoutSubmodules: true
pulumiVersionFile: .pulumi.version
parallel: 3
lint: false
enableChangelog: true
envOverride:
  AWS_REGION: us-west-2
  PULUMI_API: "https://api.pulumi-staging.io"
esc:
  enabled: true
