before:
  hooks:
    - make init_submodules
    - make codegen
    - make generate_schema
builds:
    - goos:
        - darwin
        - windows
        - linux
      goarch:
        - amd64
        - arm64
      ldflags: -X github.com/pulumi/pulumi-aws-native/provider/version.Version={{.Tag}}
      binary: cf2pulumi
      dir: provider
      main: ./cmd/cf2pulumi/
archives:
  - name_template: >-
      {{- .Binary }}-
      {{- .Tag }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}x86
      {{- else }}{{ .Arch }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
project_name: cf2pulumi
brews:
  -
    name: cf2pulumi
    repository:
      owner: pulumi
      name: homebrew-tap
    commit_author:
      name: pulumi-bot
      email: bot@pulumi.com
    homepage: "https://pulumi.com"
    description: "A tool to convert CloudFormation Templates to Pulumi programs"
    folder: Formula
    license: Apache-2.0
    test: |
      system "#{bin}/cf2pulumi version"
