coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
component_management:
  individual_components:
    - component_id: provider
      name: provider
      paths:
        - provider/**
