// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudformation.KinesisAnalyticsV2.Outputs
{

    [OutputType]
    public sealed class ApplicationInputLambdaProcessor
    {
        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalyticsv2-application-inputlambdaprocessor.html#cfn-kinesisanalyticsv2-application-inputlambdaprocessor-resourcearn
        /// </summary>
        public readonly string ResourceARN;

        [OutputConstructor]
        private ApplicationInputLambdaProcessor(string ResourceARN)
        {
            this.ResourceARN = ResourceARN;
        }
    }
}
