// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.KinesisAnalyticsV2.Outputs
{

    [OutputType]
    public sealed class ApplicationZeppelinApplicationConfiguration
    {
        public readonly Outputs.ApplicationCatalogConfiguration? CatalogConfiguration;
        public readonly Outputs.ApplicationCustomArtifactsConfiguration? CustomArtifactsConfiguration;
        public readonly Outputs.ApplicationDeployAsApplicationConfiguration? DeployAsApplicationConfiguration;
        public readonly Outputs.ApplicationZeppelinMonitoringConfiguration? MonitoringConfiguration;

        [OutputConstructor]
        private ApplicationZeppelinApplicationConfiguration(
            Outputs.ApplicationCatalogConfiguration? catalogConfiguration,

            Outputs.ApplicationCustomArtifactsConfiguration? customArtifactsConfiguration,

            Outputs.ApplicationDeployAsApplicationConfiguration? deployAsApplicationConfiguration,

            Outputs.ApplicationZeppelinMonitoringConfiguration? monitoringConfiguration)
        {
            CatalogConfiguration = catalogConfiguration;
            CustomArtifactsConfiguration = customArtifactsConfiguration;
            DeployAsApplicationConfiguration = deployAsApplicationConfiguration;
            MonitoringConfiguration = monitoringConfiguration;
        }
    }
}
