// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

/**
 * Resource schema for AWS::ImageBuilder::ImageRecipe
 */
export function getImageRecipe(args: GetImageRecipeArgs, opts?: pulumi.InvokeOptions): Promise<GetImageRecipeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aws-native:imagebuilder:getImageRecipe", {
        "arn": args.arn,
    }, opts);
}

export interface GetImageRecipeArgs {
    /**
     * The Amazon Resource Name (ARN) of the image recipe.
     */
    arn: string;
}

export interface GetImageRecipeResult {
    /**
     * Specify additional settings and launch scripts for your build instances.
     */
    readonly additionalInstanceConfiguration?: outputs.imagebuilder.ImageRecipeAdditionalInstanceConfiguration;
    /**
     * The tags to apply to the AMI created by this image recipe.
     */
    readonly amiTags?: {[key: string]: string};
    /**
     * The Amazon Resource Name (ARN) of the image recipe.
     */
    readonly arn?: string;
    /**
     * The latest version references of the image recipe.
     */
    readonly latestVersion?: outputs.imagebuilder.ImageRecipeLatestVersion;
    /**
     * The tags of the image recipe.
     */
    readonly tags?: {[key: string]: string};
}
/**
 * Resource schema for AWS::ImageBuilder::ImageRecipe
 */
export function getImageRecipeOutput(args: GetImageRecipeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetImageRecipeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aws-native:imagebuilder:getImageRecipe", {
        "arn": args.arn,
    }, opts);
}

export interface GetImageRecipeOutputArgs {
    /**
     * The Amazon Resource Name (ARN) of the image recipe.
     */
    arn: pulumi.Input<string>;
}
