// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cloudformation.WAFv2.Inputs
{

    /// <summary>
    /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html
    /// </summary>
    public sealed class RuleGroupStatementOneArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-andstatement
        /// </summary>
        [Input("AndStatement")]
        public Input<Inputs.RuleGroupAndStatementOneArgs>? AndStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-bytematchstatement
        /// </summary>
        [Input("ByteMatchStatement")]
        public Input<Inputs.RuleGroupByteMatchStatementArgs>? ByteMatchStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-geomatchstatement
        /// </summary>
        [Input("GeoMatchStatement")]
        public Input<Inputs.RuleGroupGeoMatchStatementArgs>? GeoMatchStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-ipsetreferencestatement
        /// </summary>
        [Input("IPSetReferenceStatement")]
        public Input<Inputs.RuleGroupIPSetReferenceStatementArgs>? IPSetReferenceStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-notstatement
        /// </summary>
        [Input("NotStatement")]
        public Input<Inputs.RuleGroupNotStatementOneArgs>? NotStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-orstatement
        /// </summary>
        [Input("OrStatement")]
        public Input<Inputs.RuleGroupOrStatementOneArgs>? OrStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-ratebasedstatement
        /// </summary>
        [Input("RateBasedStatement")]
        public Input<Inputs.RuleGroupRateBasedStatementOneArgs>? RateBasedStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-regexpatternsetreferencestatement
        /// </summary>
        [Input("RegexPatternSetReferenceStatement")]
        public Input<Inputs.RuleGroupRegexPatternSetReferenceStatementArgs>? RegexPatternSetReferenceStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-sizeconstraintstatement
        /// </summary>
        [Input("SizeConstraintStatement")]
        public Input<Inputs.RuleGroupSizeConstraintStatementArgs>? SizeConstraintStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-sqlimatchstatement
        /// </summary>
        [Input("SqliMatchStatement")]
        public Input<Inputs.RuleGroupSqliMatchStatementArgs>? SqliMatchStatement { get; set; }

        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-rulegroup-statementone.html#cfn-wafv2-rulegroup-statementone-xssmatchstatement
        /// </summary>
        [Input("XssMatchStatement")]
        public Input<Inputs.RuleGroupXssMatchStatementArgs>? XssMatchStatement { get; set; }

        public RuleGroupStatementOneArgs()
        {
        }
    }
}
