// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Ec2.Inputs
{

    /// <summary>
    /// Specifies a Diffie-Hellman group number for the VPN tunnel for phase 1 IKE negotiations.
    /// </summary>
    public sealed class VpnConnectionPhase1dhGroupNumbersRequestListValueArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Diffie-Hellmann group number.
        /// </summary>
        [Input("value")]
        public Input<int>? Value { get; set; }

        public VpnConnectionPhase1dhGroupNumbersRequestListValueArgs()
        {
        }
        public static new VpnConnectionPhase1dhGroupNumbersRequestListValueArgs Empty => new VpnConnectionPhase1dhGroupNumbersRequestListValueArgs();
    }
}
