// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.AwsNative.CloudWatch
{
    /// <summary>
    /// The current status of the AlarmMuteRule
    /// </summary>
    [EnumType]
    public readonly struct AlarmMuteRuleStatus : IEquatable<AlarmMuteRuleStatus>
    {
        private readonly string _value;

        private AlarmMuteRuleStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static AlarmMuteRuleStatus Scheduled { get; } = new AlarmMuteRuleStatus("SCHEDULED");
        public static AlarmMuteRuleStatus Active { get; } = new AlarmMuteRuleStatus("ACTIVE");
        public static AlarmMuteRuleStatus Expired { get; } = new AlarmMuteRuleStatus("EXPIRED");

        public static bool operator ==(AlarmMuteRuleStatus left, AlarmMuteRuleStatus right) => left.Equals(right);
        public static bool operator !=(AlarmMuteRuleStatus left, AlarmMuteRuleStatus right) => !left.Equals(right);

        public static explicit operator string(AlarmMuteRuleStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is AlarmMuteRuleStatus other && Equals(other);
        public bool Equals(AlarmMuteRuleStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// The current state of the rule. Valid values are `ENABLED` and `DISABLED` .
    /// </summary>
    [EnumType]
    public readonly struct InsightRuleRuleState : IEquatable<InsightRuleRuleState>
    {
        private readonly string _value;

        private InsightRuleRuleState(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static InsightRuleRuleState Enabled { get; } = new InsightRuleRuleState("ENABLED");
        public static InsightRuleRuleState Disabled { get; } = new InsightRuleRuleState("DISABLED");

        public static bool operator ==(InsightRuleRuleState left, InsightRuleRuleState right) => left.Equals(right);
        public static bool operator !=(InsightRuleRuleState left, InsightRuleRuleState right) => !left.Equals(right);

        public static explicit operator string(InsightRuleRuleState value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is InsightRuleRuleState other && Equals(other);
        public bool Equals(InsightRuleRuleState other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// Current status of OTel enrichment (RUNNING or STOPPED).
    /// </summary>
    [EnumType]
    public readonly struct OTelEnrichmentStatus : IEquatable<OTelEnrichmentStatus>
    {
        private readonly string _value;

        private OTelEnrichmentStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static OTelEnrichmentStatus Running { get; } = new OTelEnrichmentStatus("RUNNING");
        public static OTelEnrichmentStatus Stopped { get; } = new OTelEnrichmentStatus("STOPPED");

        public static bool operator ==(OTelEnrichmentStatus left, OTelEnrichmentStatus right) => left.Equals(right);
        public static bool operator !=(OTelEnrichmentStatus left, OTelEnrichmentStatus right) => !left.Equals(right);

        public static explicit operator string(OTelEnrichmentStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is OTelEnrichmentStatus other && Equals(other);
        public bool Equals(OTelEnrichmentStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
