// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsnative.mediapackage.outputs;

import com.pulumi.awsnative.mediapackage.outputs.ChannelHlsIngest;
import com.pulumi.awsnative.mediapackage.outputs.ChannelLogConfiguration;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetChannelResult {
    /**
     * @return The Amazon Resource Name (ARN) assigned to the Channel.
     * 
     */
    private @Nullable String arn;
    /**
     * @return A short text description of the Channel.
     * 
     */
    private @Nullable String description;
    /**
     * @return The configuration parameters for egress access logging.
     * 
     */
    private @Nullable ChannelLogConfiguration egressAccessLogs;
    /**
     * @return A short text description of the Channel.
     * 
     */
    private @Nullable ChannelHlsIngest hlsIngest;
    /**
     * @return The configuration parameters for egress access logging.
     * 
     */
    private @Nullable ChannelLogConfiguration ingressAccessLogs;

    private GetChannelResult() {}
    /**
     * @return The Amazon Resource Name (ARN) assigned to the Channel.
     * 
     */
    public Optional<String> arn() {
        return Optional.ofNullable(this.arn);
    }
    /**
     * @return A short text description of the Channel.
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The configuration parameters for egress access logging.
     * 
     */
    public Optional<ChannelLogConfiguration> egressAccessLogs() {
        return Optional.ofNullable(this.egressAccessLogs);
    }
    /**
     * @return A short text description of the Channel.
     * 
     */
    public Optional<ChannelHlsIngest> hlsIngest() {
        return Optional.ofNullable(this.hlsIngest);
    }
    /**
     * @return The configuration parameters for egress access logging.
     * 
     */
    public Optional<ChannelLogConfiguration> ingressAccessLogs() {
        return Optional.ofNullable(this.ingressAccessLogs);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetChannelResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String arn;
        private @Nullable String description;
        private @Nullable ChannelLogConfiguration egressAccessLogs;
        private @Nullable ChannelHlsIngest hlsIngest;
        private @Nullable ChannelLogConfiguration ingressAccessLogs;
        public Builder() {}
        public Builder(GetChannelResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.arn = defaults.arn;
    	      this.description = defaults.description;
    	      this.egressAccessLogs = defaults.egressAccessLogs;
    	      this.hlsIngest = defaults.hlsIngest;
    	      this.ingressAccessLogs = defaults.ingressAccessLogs;
        }

        @CustomType.Setter
        public Builder arn(@Nullable String arn) {
            this.arn = arn;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder egressAccessLogs(@Nullable ChannelLogConfiguration egressAccessLogs) {
            this.egressAccessLogs = egressAccessLogs;
            return this;
        }
        @CustomType.Setter
        public Builder hlsIngest(@Nullable ChannelHlsIngest hlsIngest) {
            this.hlsIngest = hlsIngest;
            return this;
        }
        @CustomType.Setter
        public Builder ingressAccessLogs(@Nullable ChannelLogConfiguration ingressAccessLogs) {
            this.ingressAccessLogs = ingressAccessLogs;
            return this;
        }
        public GetChannelResult build() {
            final var o = new GetChannelResult();
            o.arn = arn;
            o.description = description;
            o.egressAccessLogs = egressAccessLogs;
            o.hlsIngest = hlsIngest;
            o.ingressAccessLogs = ingressAccessLogs;
            return o;
        }
    }
}
