// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsnative.quicksight.inputs;

import com.pulumi.awsnative.quicksight.inputs.ThemeBorderStyleArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * &lt;p&gt;Display options related to tiles on a sheet.&lt;/p&gt;
 * 
 */
public final class ThemeTileStyleArgs extends com.pulumi.resources.ResourceArgs {

    public static final ThemeTileStyleArgs Empty = new ThemeTileStyleArgs();

    @Import(name="border")
    private @Nullable Output<ThemeBorderStyleArgs> border;

    public Optional<Output<ThemeBorderStyleArgs>> border() {
        return Optional.ofNullable(this.border);
    }

    private ThemeTileStyleArgs() {}

    private ThemeTileStyleArgs(ThemeTileStyleArgs $) {
        this.border = $.border;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ThemeTileStyleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ThemeTileStyleArgs $;

        public Builder() {
            $ = new ThemeTileStyleArgs();
        }

        public Builder(ThemeTileStyleArgs defaults) {
            $ = new ThemeTileStyleArgs(Objects.requireNonNull(defaults));
        }

        public Builder border(@Nullable Output<ThemeBorderStyleArgs> border) {
            $.border = border;
            return this;
        }

        public Builder border(ThemeBorderStyleArgs border) {
            return border(Output.of(border));
        }

        public ThemeTileStyleArgs build() {
            return $;
        }
    }

}
