// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Ec2
{
    public static class GetSecondaryNetwork
    {
        /// <summary>
        /// Resource Type definition for AWS::EC2::SecondaryNetwork. Creates a secondary network for RDMA (Remote Direct Memory Access) connectivity.
        /// </summary>
        public static Task<GetSecondaryNetworkResult> InvokeAsync(GetSecondaryNetworkArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSecondaryNetworkResult>("aws-native:ec2:getSecondaryNetwork", args ?? new GetSecondaryNetworkArgs(), options.WithDefaults());

        /// <summary>
        /// Resource Type definition for AWS::EC2::SecondaryNetwork. Creates a secondary network for RDMA (Remote Direct Memory Access) connectivity.
        /// </summary>
        public static Output<GetSecondaryNetworkResult> Invoke(GetSecondaryNetworkInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecondaryNetworkResult>("aws-native:ec2:getSecondaryNetwork", args ?? new GetSecondaryNetworkInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Resource Type definition for AWS::EC2::SecondaryNetwork. Creates a secondary network for RDMA (Remote Direct Memory Access) connectivity.
        /// </summary>
        public static Output<GetSecondaryNetworkResult> Invoke(GetSecondaryNetworkInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSecondaryNetworkResult>("aws-native:ec2:getSecondaryNetwork", args ?? new GetSecondaryNetworkInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSecondaryNetworkArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The Amazon Resource Name (ARN) of the secondary network.
        /// </summary>
        [Input("secondaryNetworkArn", required: true)]
        public string SecondaryNetworkArn { get; set; } = null!;

        public GetSecondaryNetworkArgs()
        {
        }
        public static new GetSecondaryNetworkArgs Empty => new GetSecondaryNetworkArgs();
    }

    public sealed class GetSecondaryNetworkInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The Amazon Resource Name (ARN) of the secondary network.
        /// </summary>
        [Input("secondaryNetworkArn", required: true)]
        public Input<string> SecondaryNetworkArn { get; set; } = null!;

        public GetSecondaryNetworkInvokeArgs()
        {
        }
        public static new GetSecondaryNetworkInvokeArgs Empty => new GetSecondaryNetworkInvokeArgs();
    }


    [OutputType]
    public sealed class GetSecondaryNetworkResult
    {
        /// <summary>
        /// Information about the IPv4 CIDR blocks associated with the secondary network.
        /// </summary>
        public readonly ImmutableArray<Outputs.SecondaryNetworkIpv4CidrBlockAssociation> Ipv4CidrBlockAssociations;
        /// <summary>
        /// The ID of the Amazon Web Services account that owns the secondary network.
        /// </summary>
        public readonly string? OwnerId;
        /// <summary>
        /// The Amazon Resource Name (ARN) of the secondary network.
        /// </summary>
        public readonly string? SecondaryNetworkArn;
        /// <summary>
        /// The ID of the secondary network.
        /// </summary>
        public readonly string? SecondaryNetworkId;
        /// <summary>
        /// The tags for the secondary network.
        /// </summary>
        public readonly ImmutableArray<Pulumi.AwsNative.Outputs.Tag> Tags;

        [OutputConstructor]
        private GetSecondaryNetworkResult(
            ImmutableArray<Outputs.SecondaryNetworkIpv4CidrBlockAssociation> ipv4CidrBlockAssociations,

            string? ownerId,

            string? secondaryNetworkArn,

            string? secondaryNetworkId,

            ImmutableArray<Pulumi.AwsNative.Outputs.Tag> tags)
        {
            Ipv4CidrBlockAssociations = ipv4CidrBlockAssociations;
            OwnerId = ownerId;
            SecondaryNetworkArn = secondaryNetworkArn;
            SecondaryNetworkId = secondaryNetworkId;
            Tags = tags;
        }
    }
}
