// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.DataZone.Inputs
{

    public sealed class PolicyGrantProjectGrantFilterPropertiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("domainUnitFilter", required: true)]
        public Input<Inputs.PolicyGrantDomainUnitFilterForProjectArgs> DomainUnitFilter { get; set; } = null!;

        public PolicyGrantProjectGrantFilterPropertiesArgs()
        {
        }
        public static new PolicyGrantProjectGrantFilterPropertiesArgs Empty => new PolicyGrantProjectGrantFilterPropertiesArgs();
    }
}
