// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.CloudFront.Outputs
{

    [OutputType]
    public sealed class DistributionTenantCustomizations
    {
        /// <summary>
        /// The AWS Certificate Manager (ACM) certificate.
        /// </summary>
        public readonly Outputs.DistributionTenantCertificate? Certificate;
        /// <summary>
        /// The geographic restrictions.
        /// </summary>
        public readonly Outputs.DistributionTenantGeoRestrictionCustomization? GeoRestrictions;
        /// <summary>
        /// The AWS WAF web ACL.
        /// </summary>
        public readonly Outputs.DistributionTenantWebAclCustomization? WebAcl;

        [OutputConstructor]
        private DistributionTenantCustomizations(
            Outputs.DistributionTenantCertificate? certificate,

            Outputs.DistributionTenantGeoRestrictionCustomization? geoRestrictions,

            Outputs.DistributionTenantWebAclCustomization? webAcl)
        {
            Certificate = certificate;
            GeoRestrictions = geoRestrictions;
            WebAcl = webAcl;
        }
    }
}
