// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.AppFlow.Inputs
{

    public sealed class ConnectorProfileCustomConnectorProfilePropertiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("oAuth2Properties")]
        public Input<Inputs.ConnectorProfileOAuth2PropertiesArgs>? OAuth2Properties { get; set; }

        [Input("profileProperties")]
        private InputMap<string>? _profileProperties;
        public InputMap<string> ProfileProperties
        {
            get => _profileProperties ?? (_profileProperties = new InputMap<string>());
            set => _profileProperties = value;
        }

        public ConnectorProfileCustomConnectorProfilePropertiesArgs()
        {
        }
        public static new ConnectorProfileCustomConnectorProfilePropertiesArgs Empty => new ConnectorProfileCustomConnectorProfilePropertiesArgs();
    }
}
