// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.FSx.Outputs
{

    /// <summary>
    /// Specifies the type of updated objects (new, changed, deleted) that will be automatically exported from your file system to the linked S3 bucket.
    /// </summary>
    [OutputType]
    public sealed class DataRepositoryAssociationAutoExportPolicy
    {
        public readonly ImmutableArray<Pulumi.AwsNative.FSx.DataRepositoryAssociationEventType> Events;

        [OutputConstructor]
        private DataRepositoryAssociationAutoExportPolicy(ImmutableArray<Pulumi.AwsNative.FSx.DataRepositoryAssociationEventType> events)
        {
            Events = events;
        }
    }
}
