// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Ecs.Inputs
{

    /// <summary>
    /// The FireLens configuration for the container. This is used to specify and configure a log router for container logs. For more information, see [Custom log routing](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html) in the *Amazon Elastic Container Service Developer Guide*.
    /// </summary>
    public sealed class DaemonTaskDefinitionFirelensConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("options")]
        private InputMap<string>? _options;

        /// <summary>
        /// The options to use when configuring the log router. This field is optional and can be used to specify a custom configuration file or to add additional metadata, such as the task, task definition, cluster, and container instance details to the log event. If specified, the syntax to use is ``"options":{"enable-ecs-log-metadata":"true|false","config-file-type:"s3|file","config-file-value":"arn:aws:s3:::mybucket/fluent.conf|filepath"}``. For more information, see [Creating a task definition that uses a FireLens configuration](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html#firelens-taskdef) in the *Amazon Elastic Container Service Developer Guide*.
        ///   Tasks hosted on FARGATElong only support the ``file`` configuration file type.
        /// </summary>
        public InputMap<string> Options
        {
            get => _options ?? (_options = new InputMap<string>());
            set => _options = value;
        }

        /// <summary>
        /// The log router to use. The valid values are ``fluentd`` or ``fluentbit``.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public DaemonTaskDefinitionFirelensConfigurationArgs()
        {
        }
        public static new DaemonTaskDefinitionFirelensConfigurationArgs Empty => new DaemonTaskDefinitionFirelensConfigurationArgs();
    }
}
