// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.LakeFormation.Outputs
{

    /// <summary>
    /// A structure that describes certain columns on certain rows.
    /// </summary>
    [OutputType]
    public sealed class PrincipalPermissionsDataCellsFilterResource
    {
        /// <summary>
        /// A database in the GLUDC.
        /// </summary>
        public readonly string DatabaseName;
        /// <summary>
        /// The name given by the user to the data filter cell.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of the catalog to which the table belongs.
        /// </summary>
        public readonly string TableCatalogId;
        /// <summary>
        /// The name of the table.
        /// </summary>
        public readonly string TableName;

        [OutputConstructor]
        private PrincipalPermissionsDataCellsFilterResource(
            string databaseName,

            string name,

            string tableCatalogId,

            string tableName)
        {
            DatabaseName = databaseName;
            Name = name;
            TableCatalogId = tableCatalogId;
            TableName = tableName;
        }
    }
}
