// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.BedrockAgentCore.Inputs
{

    /// <summary>
    /// Input configuration for a custom OAuth2 provider
    /// </summary>
    public sealed class OAuth2CredentialProviderCustomOauth2ProviderConfigInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The client ID for the custom OAuth2 provider
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// The client secret for the custom OAuth2 provider
        /// </summary>
        [Input("clientSecret")]
        public Input<string>? ClientSecret { get; set; }

        [Input("oauthDiscovery", required: true)]
        public Input<Inputs.OAuth2CredentialProviderOauth2DiscoveryArgs> OauthDiscovery { get; set; } = null!;

        [Input("onBehalfOfTokenExchangeConfig")]
        public Input<Inputs.OAuth2CredentialProviderOnBehalfOfTokenExchangeConfigArgs>? OnBehalfOfTokenExchangeConfig { get; set; }

        public OAuth2CredentialProviderCustomOauth2ProviderConfigInputArgs()
        {
        }
        public static new OAuth2CredentialProviderCustomOauth2ProviderConfigInputArgs Empty => new OAuth2CredentialProviderCustomOauth2ProviderConfigInputArgs();
    }
}
