// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.IoT.Inputs
{

    public sealed class TopicRuleRepublishActionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// MQTT Version 5.0 headers information. For more information, see [MQTT](https://docs.aws.amazon.com//iot/latest/developerguide/mqtt.html) in the IoT Core Developer Guide.
        /// </summary>
        [Input("headers")]
        public Input<Inputs.TopicRuleRepublishActionHeadersArgs>? Headers { get; set; }

        /// <summary>
        /// The Quality of Service (QoS) level to use when republishing messages. The default value is 0.
        /// </summary>
        [Input("qos")]
        public Input<int>? Qos { get; set; }

        /// <summary>
        /// The ARN of the IAM role that grants access.
        /// </summary>
        [Input("roleArn", required: true)]
        public Input<string> RoleArn { get; set; } = null!;

        /// <summary>
        /// The name of the MQTT topic.
        /// </summary>
        [Input("topic", required: true)]
        public Input<string> Topic { get; set; } = null!;

        public TopicRuleRepublishActionArgs()
        {
        }
        public static new TopicRuleRepublishActionArgs Empty => new TopicRuleRepublishActionArgs();
    }
}
