// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.ConnectCampaignsV2.Outputs
{

    /// <summary>
    /// Progressive config
    /// </summary>
    [OutputType]
    public sealed class CampaignProgressiveConfig
    {
        /// <summary>
        /// Bandwidth allocation for the progressive outbound mode.
        /// </summary>
        public readonly double BandwidthAllocation;

        [OutputConstructor]
        private CampaignProgressiveConfig(double bandwidthAllocation)
        {
            BandwidthAllocation = bandwidthAllocation;
        }
    }
}
