// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.ECS.Outputs
{

    [OutputType]
    public sealed class TaskDefinitionAuthorizationConfig
    {
        public readonly string? AccessPointId;
        public readonly Pulumi.AwsNative.ECS.TaskDefinitionAuthorizationConfigIAM? IAM;

        [OutputConstructor]
        private TaskDefinitionAuthorizationConfig(
            string? accessPointId,

            Pulumi.AwsNative.ECS.TaskDefinitionAuthorizationConfigIAM? iAM)
        {
            AccessPointId = accessPointId;
            IAM = iAM;
        }
    }
}
