// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Fms.Outputs
{

    /// <summary>
    /// A resource tag.
    /// </summary>
    [OutputType]
    public sealed class PolicyResourceTag
    {
        /// <summary>
        /// The resource tag key.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The resource tag value.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private PolicyResourceTag(
            string key,

            string? value)
        {
            Key = key;
            Value = value;
        }
    }
}
