// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ec2

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-aws-native/sdk/go/aws"
	"github.com/pulumi/pulumi-aws-native/sdk/go/aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Resource schema for AWS::EC2::NetworkInsightsPath
func LookupNetworkInsightsPath(ctx *pulumi.Context, args *LookupNetworkInsightsPathArgs, opts ...pulumi.InvokeOption) (*LookupNetworkInsightsPathResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNetworkInsightsPathResult
	err := ctx.Invoke("aws-native:ec2:getNetworkInsightsPath", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupNetworkInsightsPathArgs struct {
	// The ID of the path.
	NetworkInsightsPathId string `pulumi:"networkInsightsPathId"`
}

type LookupNetworkInsightsPathResult struct {
	// The time stamp when the path was created.
	CreatedDate *string `pulumi:"createdDate"`
	// The Amazon Resource Name (ARN) of the destination.
	DestinationArn *string `pulumi:"destinationArn"`
	// The Amazon Resource Name (ARN) of the path.
	NetworkInsightsPathArn *string `pulumi:"networkInsightsPathArn"`
	// The ID of the path.
	NetworkInsightsPathId *string `pulumi:"networkInsightsPathId"`
	// The Amazon Resource Name (ARN) of the source.
	SourceArn *string `pulumi:"sourceArn"`
	// The tags to add to the path.
	Tags []aws.Tag `pulumi:"tags"`
}

func LookupNetworkInsightsPathOutput(ctx *pulumi.Context, args LookupNetworkInsightsPathOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkInsightsPathResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkInsightsPathResultOutput, error) {
			args := v.(LookupNetworkInsightsPathArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("aws-native:ec2:getNetworkInsightsPath", args, LookupNetworkInsightsPathResultOutput{}, options).(LookupNetworkInsightsPathResultOutput), nil
		}).(LookupNetworkInsightsPathResultOutput)
}

type LookupNetworkInsightsPathOutputArgs struct {
	// The ID of the path.
	NetworkInsightsPathId pulumi.StringInput `pulumi:"networkInsightsPathId"`
}

func (LookupNetworkInsightsPathOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkInsightsPathArgs)(nil)).Elem()
}

type LookupNetworkInsightsPathResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkInsightsPathResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkInsightsPathResult)(nil)).Elem()
}

func (o LookupNetworkInsightsPathResultOutput) ToLookupNetworkInsightsPathResultOutput() LookupNetworkInsightsPathResultOutput {
	return o
}

func (o LookupNetworkInsightsPathResultOutput) ToLookupNetworkInsightsPathResultOutputWithContext(ctx context.Context) LookupNetworkInsightsPathResultOutput {
	return o
}

// The time stamp when the path was created.
func (o LookupNetworkInsightsPathResultOutput) CreatedDate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkInsightsPathResult) *string { return v.CreatedDate }).(pulumi.StringPtrOutput)
}

// The Amazon Resource Name (ARN) of the destination.
func (o LookupNetworkInsightsPathResultOutput) DestinationArn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkInsightsPathResult) *string { return v.DestinationArn }).(pulumi.StringPtrOutput)
}

// The Amazon Resource Name (ARN) of the path.
func (o LookupNetworkInsightsPathResultOutput) NetworkInsightsPathArn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkInsightsPathResult) *string { return v.NetworkInsightsPathArn }).(pulumi.StringPtrOutput)
}

// The ID of the path.
func (o LookupNetworkInsightsPathResultOutput) NetworkInsightsPathId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkInsightsPathResult) *string { return v.NetworkInsightsPathId }).(pulumi.StringPtrOutput)
}

// The Amazon Resource Name (ARN) of the source.
func (o LookupNetworkInsightsPathResultOutput) SourceArn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkInsightsPathResult) *string { return v.SourceArn }).(pulumi.StringPtrOutput)
}

// The tags to add to the path.
func (o LookupNetworkInsightsPathResultOutput) Tags() aws.TagArrayOutput {
	return o.ApplyT(func(v LookupNetworkInsightsPathResult) []aws.Tag { return v.Tags }).(aws.TagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkInsightsPathResultOutput{})
}
