// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsnative.iotsitewise.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetDashboardArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDashboardArgs Empty = new GetDashboardArgs();

    /**
     * The ID of the dashboard.
     * 
     */
    @Import(name="dashboardId", required=true)
    private Output<String> dashboardId;

    /**
     * @return The ID of the dashboard.
     * 
     */
    public Output<String> dashboardId() {
        return this.dashboardId;
    }

    private GetDashboardArgs() {}

    private GetDashboardArgs(GetDashboardArgs $) {
        this.dashboardId = $.dashboardId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDashboardArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDashboardArgs $;

        public Builder() {
            $ = new GetDashboardArgs();
        }

        public Builder(GetDashboardArgs defaults) {
            $ = new GetDashboardArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param dashboardId The ID of the dashboard.
         * 
         * @return builder
         * 
         */
        public Builder dashboardId(Output<String> dashboardId) {
            $.dashboardId = dashboardId;
            return this;
        }

        /**
         * @param dashboardId The ID of the dashboard.
         * 
         * @return builder
         * 
         */
        public Builder dashboardId(String dashboardId) {
            return dashboardId(Output.of(dashboardId));
        }

        public GetDashboardArgs build() {
            $.dashboardId = Objects.requireNonNull($.dashboardId, "expected parameter 'dashboardId' to be non-null");
            return $;
        }
    }

}
