// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Ses.Inputs
{

    public sealed class MailManagerIngressPointPrivateNetworkConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("vpcEndpointId", required: true)]
        public Input<string> VpcEndpointId { get; set; } = null!;

        public MailManagerIngressPointPrivateNetworkConfigurationArgs()
        {
        }
        public static new MailManagerIngressPointPrivateNetworkConfigurationArgs Empty => new MailManagerIngressPointPrivateNetworkConfigurationArgs();
    }
}
