// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.S3.Inputs
{

    public sealed class StorageLensPrefixLevelStorageMetricsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies whether prefix-level storage metrics are enabled or disabled.
        /// </summary>
        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        /// <summary>
        /// This property identifies whether the details of the prefix-level storage metrics for S3 Storage Lens are enabled.
        /// </summary>
        [Input("selectionCriteria")]
        public Input<Inputs.StorageLensSelectionCriteriaArgs>? SelectionCriteria { get; set; }

        public StorageLensPrefixLevelStorageMetricsArgs()
        {
        }
        public static new StorageLensPrefixLevelStorageMetricsArgs Empty => new StorageLensPrefixLevelStorageMetricsArgs();
    }
}
