// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.AmplifyUiBuilder.Outputs
{

    [OutputType]
    public sealed class FormFileUploaderFieldConfig
    {
        /// <summary>
        /// The file types that are allowed to be uploaded by the file uploader. Provide this information in an array of strings specifying the valid file extensions.
        /// </summary>
        public readonly ImmutableArray<string> AcceptedFileTypes;
        /// <summary>
        /// The access level to assign to the uploaded files in the Amazon S3 bucket where they are stored. The valid values for this property are `private` , `protected` , or `public` . For detailed information about the permissions associated with each access level, see [File access levels](https://docs.aws.amazon.com/https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js/) in the *Amplify documentation* .
        /// </summary>
        public readonly Pulumi.AwsNative.AmplifyUiBuilder.FormStorageAccessLevel AccessLevel;
        /// <summary>
        /// Allows the file upload operation to be paused and resumed. The default value is `false` .
        /// 
        /// When `isResumable` is set to `true` , the file uploader uses a multipart upload to break the files into chunks before upload. The progress of the upload isn't continuous, because the file uploader uploads a chunk at a time.
        /// </summary>
        public readonly bool? IsResumable;
        /// <summary>
        /// Specifies the maximum number of files that can be selected to upload. The default value is an unlimited number of files.
        /// </summary>
        public readonly double? MaxFileCount;
        /// <summary>
        /// The maximum file size in bytes that the file uploader will accept. The default value is an unlimited file size.
        /// </summary>
        public readonly double? MaxSize;
        /// <summary>
        /// Specifies whether to display or hide the image preview after selecting a file for upload. The default value is `true` to display the image preview.
        /// </summary>
        public readonly bool? ShowThumbnails;

        [OutputConstructor]
        private FormFileUploaderFieldConfig(
            ImmutableArray<string> acceptedFileTypes,

            Pulumi.AwsNative.AmplifyUiBuilder.FormStorageAccessLevel accessLevel,

            bool? isResumable,

            double? maxFileCount,

            double? maxSize,

            bool? showThumbnails)
        {
            AcceptedFileTypes = acceptedFileTypes;
            AccessLevel = accessLevel;
            IsResumable = isResumable;
            MaxFileCount = maxFileCount;
            MaxSize = maxSize;
            ShowThumbnails = showThumbnails;
        }
    }
}
