// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.QuickSight.Outputs
{

    [OutputType]
    public sealed class DashboardMetricComparisonComputation
    {
        /// <summary>
        /// The ID for a computation.
        /// </summary>
        public readonly string ComputationId;
        /// <summary>
        /// The field that is used in a metric comparison from value setup.
        /// </summary>
        public readonly Outputs.DashboardMeasureField? FromValue;
        /// <summary>
        /// The name of a computation.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The field that is used in a metric comparison to value setup.
        /// </summary>
        public readonly Outputs.DashboardMeasureField? TargetValue;
        /// <summary>
        /// The time field that is used in a computation.
        /// </summary>
        public readonly Outputs.DashboardDimensionField? Time;

        [OutputConstructor]
        private DashboardMetricComparisonComputation(
            string computationId,

            Outputs.DashboardMeasureField? fromValue,

            string? name,

            Outputs.DashboardMeasureField? targetValue,

            Outputs.DashboardDimensionField? time)
        {
            ComputationId = computationId;
            FromValue = fromValue;
            Name = name;
            TargetValue = targetValue;
            Time = time;
        }
    }
}
