// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.AutoScalingPlans.Outputs
{

    [OutputType]
    public sealed class ScalingPlanCustomizedLoadMetricSpecification
    {
        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscalingplans-scalingplan-customizedloadmetricspecification.html#cfn-autoscalingplans-scalingplan-customizedloadmetricspecification-dimensions
        /// </summary>
        public readonly ImmutableArray<Outputs.ScalingPlanMetricDimension> Dimensions;
        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscalingplans-scalingplan-customizedloadmetricspecification.html#cfn-autoscalingplans-scalingplan-customizedloadmetricspecification-metricname
        /// </summary>
        public readonly string MetricName;
        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscalingplans-scalingplan-customizedloadmetricspecification.html#cfn-autoscalingplans-scalingplan-customizedloadmetricspecification-namespace
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscalingplans-scalingplan-customizedloadmetricspecification.html#cfn-autoscalingplans-scalingplan-customizedloadmetricspecification-statistic
        /// </summary>
        public readonly string Statistic;
        /// <summary>
        /// http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscalingplans-scalingplan-customizedloadmetricspecification.html#cfn-autoscalingplans-scalingplan-customizedloadmetricspecification-unit
        /// </summary>
        public readonly string? Unit;

        [OutputConstructor]
        private ScalingPlanCustomizedLoadMetricSpecification(
            ImmutableArray<Outputs.ScalingPlanMetricDimension> Dimensions,

            string MetricName,

            string Namespace,

            string Statistic,

            string? Unit)
        {
            this.Dimensions = Dimensions;
            this.MetricName = MetricName;
            this.Namespace = Namespace;
            this.Statistic = Statistic;
            this.Unit = Unit;
        }
    }
}
