// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package guardduty

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-aws-native/sdk/go/aws"
	"github.com/pulumi/pulumi-aws-native/sdk/go/aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Resource Type definition for AWS::GuardDuty::TrustedEntitySet
func LookupTrustedEntitySet(ctx *pulumi.Context, args *LookupTrustedEntitySetArgs, opts ...pulumi.InvokeOption) (*LookupTrustedEntitySetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTrustedEntitySetResult
	err := ctx.Invoke("aws-native:guardduty:getTrustedEntitySet", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupTrustedEntitySetArgs struct {
	DetectorId string `pulumi:"detectorId"`
	Id         string `pulumi:"id"`
}

type LookupTrustedEntitySetResult struct {
	CreatedAt    *string `pulumi:"createdAt"`
	ErrorDetails *string `pulumi:"errorDetails"`
	// Contains information on the owner of the bucket.
	ExpectedBucketOwner *string                 `pulumi:"expectedBucketOwner"`
	Id                  *string                 `pulumi:"id"`
	Location            *string                 `pulumi:"location"`
	Name                *string                 `pulumi:"name"`
	Status              *TrustedEntitySetStatus `pulumi:"status"`
	Tags                []aws.Tag               `pulumi:"tags"`
	UpdatedAt           *string                 `pulumi:"updatedAt"`
}

func LookupTrustedEntitySetOutput(ctx *pulumi.Context, args LookupTrustedEntitySetOutputArgs, opts ...pulumi.InvokeOption) LookupTrustedEntitySetResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTrustedEntitySetResultOutput, error) {
			args := v.(LookupTrustedEntitySetArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("aws-native:guardduty:getTrustedEntitySet", args, LookupTrustedEntitySetResultOutput{}, options).(LookupTrustedEntitySetResultOutput), nil
		}).(LookupTrustedEntitySetResultOutput)
}

type LookupTrustedEntitySetOutputArgs struct {
	DetectorId pulumi.StringInput `pulumi:"detectorId"`
	Id         pulumi.StringInput `pulumi:"id"`
}

func (LookupTrustedEntitySetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTrustedEntitySetArgs)(nil)).Elem()
}

type LookupTrustedEntitySetResultOutput struct{ *pulumi.OutputState }

func (LookupTrustedEntitySetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTrustedEntitySetResult)(nil)).Elem()
}

func (o LookupTrustedEntitySetResultOutput) ToLookupTrustedEntitySetResultOutput() LookupTrustedEntitySetResultOutput {
	return o
}

func (o LookupTrustedEntitySetResultOutput) ToLookupTrustedEntitySetResultOutputWithContext(ctx context.Context) LookupTrustedEntitySetResultOutput {
	return o
}

func (o LookupTrustedEntitySetResultOutput) CreatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) *string { return v.CreatedAt }).(pulumi.StringPtrOutput)
}

func (o LookupTrustedEntitySetResultOutput) ErrorDetails() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) *string { return v.ErrorDetails }).(pulumi.StringPtrOutput)
}

// Contains information on the owner of the bucket.
func (o LookupTrustedEntitySetResultOutput) ExpectedBucketOwner() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) *string { return v.ExpectedBucketOwner }).(pulumi.StringPtrOutput)
}

func (o LookupTrustedEntitySetResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupTrustedEntitySetResultOutput) Location() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) *string { return v.Location }).(pulumi.StringPtrOutput)
}

func (o LookupTrustedEntitySetResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupTrustedEntitySetResultOutput) Status() TrustedEntitySetStatusPtrOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) *TrustedEntitySetStatus { return v.Status }).(TrustedEntitySetStatusPtrOutput)
}

func (o LookupTrustedEntitySetResultOutput) Tags() aws.TagArrayOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) []aws.Tag { return v.Tags }).(aws.TagArrayOutput)
}

func (o LookupTrustedEntitySetResultOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupTrustedEntitySetResult) *string { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTrustedEntitySetResultOutput{})
}
