// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package guardduty

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Whether the rule runs in LIVE mode (generates findings) or DRY_RUN mode (evaluates without generating findings).
type CustomDetectionRuleAssociationMode string

const (
	CustomDetectionRuleAssociationModeLive   = CustomDetectionRuleAssociationMode("LIVE")
	CustomDetectionRuleAssociationModeDryRun = CustomDetectionRuleAssociationMode("DRY_RUN")
)

func (CustomDetectionRuleAssociationMode) ElementType() reflect.Type {
	return reflect.TypeOf((*CustomDetectionRuleAssociationMode)(nil)).Elem()
}

func (e CustomDetectionRuleAssociationMode) ToCustomDetectionRuleAssociationModeOutput() CustomDetectionRuleAssociationModeOutput {
	return pulumi.ToOutput(e).(CustomDetectionRuleAssociationModeOutput)
}

func (e CustomDetectionRuleAssociationMode) ToCustomDetectionRuleAssociationModeOutputWithContext(ctx context.Context) CustomDetectionRuleAssociationModeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(CustomDetectionRuleAssociationModeOutput)
}

func (e CustomDetectionRuleAssociationMode) ToCustomDetectionRuleAssociationModePtrOutput() CustomDetectionRuleAssociationModePtrOutput {
	return e.ToCustomDetectionRuleAssociationModePtrOutputWithContext(context.Background())
}

func (e CustomDetectionRuleAssociationMode) ToCustomDetectionRuleAssociationModePtrOutputWithContext(ctx context.Context) CustomDetectionRuleAssociationModePtrOutput {
	return CustomDetectionRuleAssociationMode(e).ToCustomDetectionRuleAssociationModeOutputWithContext(ctx).ToCustomDetectionRuleAssociationModePtrOutputWithContext(ctx)
}

func (e CustomDetectionRuleAssociationMode) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e CustomDetectionRuleAssociationMode) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e CustomDetectionRuleAssociationMode) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e CustomDetectionRuleAssociationMode) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type CustomDetectionRuleAssociationModeOutput struct{ *pulumi.OutputState }

func (CustomDetectionRuleAssociationModeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CustomDetectionRuleAssociationMode)(nil)).Elem()
}

func (o CustomDetectionRuleAssociationModeOutput) ToCustomDetectionRuleAssociationModeOutput() CustomDetectionRuleAssociationModeOutput {
	return o
}

func (o CustomDetectionRuleAssociationModeOutput) ToCustomDetectionRuleAssociationModeOutputWithContext(ctx context.Context) CustomDetectionRuleAssociationModeOutput {
	return o
}

func (o CustomDetectionRuleAssociationModeOutput) ToCustomDetectionRuleAssociationModePtrOutput() CustomDetectionRuleAssociationModePtrOutput {
	return o.ToCustomDetectionRuleAssociationModePtrOutputWithContext(context.Background())
}

func (o CustomDetectionRuleAssociationModeOutput) ToCustomDetectionRuleAssociationModePtrOutputWithContext(ctx context.Context) CustomDetectionRuleAssociationModePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v CustomDetectionRuleAssociationMode) *CustomDetectionRuleAssociationMode {
		return &v
	}).(CustomDetectionRuleAssociationModePtrOutput)
}

func (o CustomDetectionRuleAssociationModeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o CustomDetectionRuleAssociationModeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e CustomDetectionRuleAssociationMode) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o CustomDetectionRuleAssociationModeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o CustomDetectionRuleAssociationModeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e CustomDetectionRuleAssociationMode) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type CustomDetectionRuleAssociationModePtrOutput struct{ *pulumi.OutputState }

func (CustomDetectionRuleAssociationModePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomDetectionRuleAssociationMode)(nil)).Elem()
}

func (o CustomDetectionRuleAssociationModePtrOutput) ToCustomDetectionRuleAssociationModePtrOutput() CustomDetectionRuleAssociationModePtrOutput {
	return o
}

func (o CustomDetectionRuleAssociationModePtrOutput) ToCustomDetectionRuleAssociationModePtrOutputWithContext(ctx context.Context) CustomDetectionRuleAssociationModePtrOutput {
	return o
}

func (o CustomDetectionRuleAssociationModePtrOutput) Elem() CustomDetectionRuleAssociationModeOutput {
	return o.ApplyT(func(v *CustomDetectionRuleAssociationMode) CustomDetectionRuleAssociationMode {
		if v != nil {
			return *v
		}
		var ret CustomDetectionRuleAssociationMode
		return ret
	}).(CustomDetectionRuleAssociationModeOutput)
}

func (o CustomDetectionRuleAssociationModePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o CustomDetectionRuleAssociationModePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *CustomDetectionRuleAssociationMode) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// CustomDetectionRuleAssociationModeInput is an input type that accepts values of the CustomDetectionRuleAssociationMode enum
// A concrete instance of `CustomDetectionRuleAssociationModeInput` can be one of the following:
//
//	CustomDetectionRuleAssociationModeLive
//	CustomDetectionRuleAssociationModeDryRun
type CustomDetectionRuleAssociationModeInput interface {
	pulumi.Input

	ToCustomDetectionRuleAssociationModeOutput() CustomDetectionRuleAssociationModeOutput
	ToCustomDetectionRuleAssociationModeOutputWithContext(context.Context) CustomDetectionRuleAssociationModeOutput
}

var customDetectionRuleAssociationModePtrType = reflect.TypeOf((**CustomDetectionRuleAssociationMode)(nil)).Elem()

type CustomDetectionRuleAssociationModePtrInput interface {
	pulumi.Input

	ToCustomDetectionRuleAssociationModePtrOutput() CustomDetectionRuleAssociationModePtrOutput
	ToCustomDetectionRuleAssociationModePtrOutputWithContext(context.Context) CustomDetectionRuleAssociationModePtrOutput
}

type customDetectionRuleAssociationModePtr string

func CustomDetectionRuleAssociationModePtr(v string) CustomDetectionRuleAssociationModePtrInput {
	return (*customDetectionRuleAssociationModePtr)(&v)
}

func (*customDetectionRuleAssociationModePtr) ElementType() reflect.Type {
	return customDetectionRuleAssociationModePtrType
}

func (in *customDetectionRuleAssociationModePtr) ToCustomDetectionRuleAssociationModePtrOutput() CustomDetectionRuleAssociationModePtrOutput {
	return pulumi.ToOutput(in).(CustomDetectionRuleAssociationModePtrOutput)
}

func (in *customDetectionRuleAssociationModePtr) ToCustomDetectionRuleAssociationModePtrOutputWithContext(ctx context.Context) CustomDetectionRuleAssociationModePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(CustomDetectionRuleAssociationModePtrOutput)
}

// Status of the feature configuration.
type DetectorCfnFeatureConfigurationStatus string

const (
	DetectorCfnFeatureConfigurationStatusEnabled  = DetectorCfnFeatureConfigurationStatus("ENABLED")
	DetectorCfnFeatureConfigurationStatusDisabled = DetectorCfnFeatureConfigurationStatus("DISABLED")
)

func (DetectorCfnFeatureConfigurationStatus) ElementType() reflect.Type {
	return reflect.TypeOf((*DetectorCfnFeatureConfigurationStatus)(nil)).Elem()
}

func (e DetectorCfnFeatureConfigurationStatus) ToDetectorCfnFeatureConfigurationStatusOutput() DetectorCfnFeatureConfigurationStatusOutput {
	return pulumi.ToOutput(e).(DetectorCfnFeatureConfigurationStatusOutput)
}

func (e DetectorCfnFeatureConfigurationStatus) ToDetectorCfnFeatureConfigurationStatusOutputWithContext(ctx context.Context) DetectorCfnFeatureConfigurationStatusOutput {
	return pulumi.ToOutputWithContext(ctx, e).(DetectorCfnFeatureConfigurationStatusOutput)
}

func (e DetectorCfnFeatureConfigurationStatus) ToDetectorCfnFeatureConfigurationStatusPtrOutput() DetectorCfnFeatureConfigurationStatusPtrOutput {
	return e.ToDetectorCfnFeatureConfigurationStatusPtrOutputWithContext(context.Background())
}

func (e DetectorCfnFeatureConfigurationStatus) ToDetectorCfnFeatureConfigurationStatusPtrOutputWithContext(ctx context.Context) DetectorCfnFeatureConfigurationStatusPtrOutput {
	return DetectorCfnFeatureConfigurationStatus(e).ToDetectorCfnFeatureConfigurationStatusOutputWithContext(ctx).ToDetectorCfnFeatureConfigurationStatusPtrOutputWithContext(ctx)
}

func (e DetectorCfnFeatureConfigurationStatus) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e DetectorCfnFeatureConfigurationStatus) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e DetectorCfnFeatureConfigurationStatus) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e DetectorCfnFeatureConfigurationStatus) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type DetectorCfnFeatureConfigurationStatusOutput struct{ *pulumi.OutputState }

func (DetectorCfnFeatureConfigurationStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DetectorCfnFeatureConfigurationStatus)(nil)).Elem()
}

func (o DetectorCfnFeatureConfigurationStatusOutput) ToDetectorCfnFeatureConfigurationStatusOutput() DetectorCfnFeatureConfigurationStatusOutput {
	return o
}

func (o DetectorCfnFeatureConfigurationStatusOutput) ToDetectorCfnFeatureConfigurationStatusOutputWithContext(ctx context.Context) DetectorCfnFeatureConfigurationStatusOutput {
	return o
}

func (o DetectorCfnFeatureConfigurationStatusOutput) ToDetectorCfnFeatureConfigurationStatusPtrOutput() DetectorCfnFeatureConfigurationStatusPtrOutput {
	return o.ToDetectorCfnFeatureConfigurationStatusPtrOutputWithContext(context.Background())
}

func (o DetectorCfnFeatureConfigurationStatusOutput) ToDetectorCfnFeatureConfigurationStatusPtrOutputWithContext(ctx context.Context) DetectorCfnFeatureConfigurationStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DetectorCfnFeatureConfigurationStatus) *DetectorCfnFeatureConfigurationStatus {
		return &v
	}).(DetectorCfnFeatureConfigurationStatusPtrOutput)
}

func (o DetectorCfnFeatureConfigurationStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o DetectorCfnFeatureConfigurationStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DetectorCfnFeatureConfigurationStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o DetectorCfnFeatureConfigurationStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DetectorCfnFeatureConfigurationStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e DetectorCfnFeatureConfigurationStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type DetectorCfnFeatureConfigurationStatusPtrOutput struct{ *pulumi.OutputState }

func (DetectorCfnFeatureConfigurationStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DetectorCfnFeatureConfigurationStatus)(nil)).Elem()
}

func (o DetectorCfnFeatureConfigurationStatusPtrOutput) ToDetectorCfnFeatureConfigurationStatusPtrOutput() DetectorCfnFeatureConfigurationStatusPtrOutput {
	return o
}

func (o DetectorCfnFeatureConfigurationStatusPtrOutput) ToDetectorCfnFeatureConfigurationStatusPtrOutputWithContext(ctx context.Context) DetectorCfnFeatureConfigurationStatusPtrOutput {
	return o
}

func (o DetectorCfnFeatureConfigurationStatusPtrOutput) Elem() DetectorCfnFeatureConfigurationStatusOutput {
	return o.ApplyT(func(v *DetectorCfnFeatureConfigurationStatus) DetectorCfnFeatureConfigurationStatus {
		if v != nil {
			return *v
		}
		var ret DetectorCfnFeatureConfigurationStatus
		return ret
	}).(DetectorCfnFeatureConfigurationStatusOutput)
}

func (o DetectorCfnFeatureConfigurationStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o DetectorCfnFeatureConfigurationStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *DetectorCfnFeatureConfigurationStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// DetectorCfnFeatureConfigurationStatusInput is an input type that accepts values of the DetectorCfnFeatureConfigurationStatus enum
// A concrete instance of `DetectorCfnFeatureConfigurationStatusInput` can be one of the following:
//
//	DetectorCfnFeatureConfigurationStatusEnabled
//	DetectorCfnFeatureConfigurationStatusDisabled
type DetectorCfnFeatureConfigurationStatusInput interface {
	pulumi.Input

	ToDetectorCfnFeatureConfigurationStatusOutput() DetectorCfnFeatureConfigurationStatusOutput
	ToDetectorCfnFeatureConfigurationStatusOutputWithContext(context.Context) DetectorCfnFeatureConfigurationStatusOutput
}

var detectorCfnFeatureConfigurationStatusPtrType = reflect.TypeOf((**DetectorCfnFeatureConfigurationStatus)(nil)).Elem()

type DetectorCfnFeatureConfigurationStatusPtrInput interface {
	pulumi.Input

	ToDetectorCfnFeatureConfigurationStatusPtrOutput() DetectorCfnFeatureConfigurationStatusPtrOutput
	ToDetectorCfnFeatureConfigurationStatusPtrOutputWithContext(context.Context) DetectorCfnFeatureConfigurationStatusPtrOutput
}

type detectorCfnFeatureConfigurationStatusPtr string

func DetectorCfnFeatureConfigurationStatusPtr(v string) DetectorCfnFeatureConfigurationStatusPtrInput {
	return (*detectorCfnFeatureConfigurationStatusPtr)(&v)
}

func (*detectorCfnFeatureConfigurationStatusPtr) ElementType() reflect.Type {
	return detectorCfnFeatureConfigurationStatusPtrType
}

func (in *detectorCfnFeatureConfigurationStatusPtr) ToDetectorCfnFeatureConfigurationStatusPtrOutput() DetectorCfnFeatureConfigurationStatusPtrOutput {
	return pulumi.ToOutput(in).(DetectorCfnFeatureConfigurationStatusPtrOutput)
}

func (in *detectorCfnFeatureConfigurationStatusPtr) ToDetectorCfnFeatureConfigurationStatusPtrOutputWithContext(ctx context.Context) DetectorCfnFeatureConfigurationStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(DetectorCfnFeatureConfigurationStatusPtrOutput)
}

// The status of your `ThreatEntitySet` . For information about valid status values, see [Understanding list statuses](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_upload-lists.html#guardduty-entity-list-statuses) in the *Amazon GuardDuty User Guide* .
type ThreatEntitySetStatus string

const (
	ThreatEntitySetStatusInactive      = ThreatEntitySetStatus("INACTIVE")
	ThreatEntitySetStatusActivating    = ThreatEntitySetStatus("ACTIVATING")
	ThreatEntitySetStatusActive        = ThreatEntitySetStatus("ACTIVE")
	ThreatEntitySetStatusDeactivating  = ThreatEntitySetStatus("DEACTIVATING")
	ThreatEntitySetStatusError         = ThreatEntitySetStatus("ERROR")
	ThreatEntitySetStatusDeletePending = ThreatEntitySetStatus("DELETE_PENDING")
	ThreatEntitySetStatusDeleted       = ThreatEntitySetStatus("DELETED")
)

type ThreatEntitySetStatusOutput struct{ *pulumi.OutputState }

func (ThreatEntitySetStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ThreatEntitySetStatus)(nil)).Elem()
}

func (o ThreatEntitySetStatusOutput) ToThreatEntitySetStatusOutput() ThreatEntitySetStatusOutput {
	return o
}

func (o ThreatEntitySetStatusOutput) ToThreatEntitySetStatusOutputWithContext(ctx context.Context) ThreatEntitySetStatusOutput {
	return o
}

func (o ThreatEntitySetStatusOutput) ToThreatEntitySetStatusPtrOutput() ThreatEntitySetStatusPtrOutput {
	return o.ToThreatEntitySetStatusPtrOutputWithContext(context.Background())
}

func (o ThreatEntitySetStatusOutput) ToThreatEntitySetStatusPtrOutputWithContext(ctx context.Context) ThreatEntitySetStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ThreatEntitySetStatus) *ThreatEntitySetStatus {
		return &v
	}).(ThreatEntitySetStatusPtrOutput)
}

func (o ThreatEntitySetStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ThreatEntitySetStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ThreatEntitySetStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ThreatEntitySetStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ThreatEntitySetStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ThreatEntitySetStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ThreatEntitySetStatusPtrOutput struct{ *pulumi.OutputState }

func (ThreatEntitySetStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ThreatEntitySetStatus)(nil)).Elem()
}

func (o ThreatEntitySetStatusPtrOutput) ToThreatEntitySetStatusPtrOutput() ThreatEntitySetStatusPtrOutput {
	return o
}

func (o ThreatEntitySetStatusPtrOutput) ToThreatEntitySetStatusPtrOutputWithContext(ctx context.Context) ThreatEntitySetStatusPtrOutput {
	return o
}

func (o ThreatEntitySetStatusPtrOutput) Elem() ThreatEntitySetStatusOutput {
	return o.ApplyT(func(v *ThreatEntitySetStatus) ThreatEntitySetStatus {
		if v != nil {
			return *v
		}
		var ret ThreatEntitySetStatus
		return ret
	}).(ThreatEntitySetStatusOutput)
}

func (o ThreatEntitySetStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ThreatEntitySetStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ThreatEntitySetStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// The status of your `TrustedEntitySet` . For information about valid status values, see [Understanding list statuses](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_upload-lists.html#guardduty-entity-list-statuses) in the *Amazon GuardDuty User Guide* .
type TrustedEntitySetStatus string

const (
	TrustedEntitySetStatusInactive      = TrustedEntitySetStatus("INACTIVE")
	TrustedEntitySetStatusActivating    = TrustedEntitySetStatus("ACTIVATING")
	TrustedEntitySetStatusActive        = TrustedEntitySetStatus("ACTIVE")
	TrustedEntitySetStatusDeactivating  = TrustedEntitySetStatus("DEACTIVATING")
	TrustedEntitySetStatusError         = TrustedEntitySetStatus("ERROR")
	TrustedEntitySetStatusDeletePending = TrustedEntitySetStatus("DELETE_PENDING")
	TrustedEntitySetStatusDeleted       = TrustedEntitySetStatus("DELETED")
)

type TrustedEntitySetStatusOutput struct{ *pulumi.OutputState }

func (TrustedEntitySetStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TrustedEntitySetStatus)(nil)).Elem()
}

func (o TrustedEntitySetStatusOutput) ToTrustedEntitySetStatusOutput() TrustedEntitySetStatusOutput {
	return o
}

func (o TrustedEntitySetStatusOutput) ToTrustedEntitySetStatusOutputWithContext(ctx context.Context) TrustedEntitySetStatusOutput {
	return o
}

func (o TrustedEntitySetStatusOutput) ToTrustedEntitySetStatusPtrOutput() TrustedEntitySetStatusPtrOutput {
	return o.ToTrustedEntitySetStatusPtrOutputWithContext(context.Background())
}

func (o TrustedEntitySetStatusOutput) ToTrustedEntitySetStatusPtrOutputWithContext(ctx context.Context) TrustedEntitySetStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v TrustedEntitySetStatus) *TrustedEntitySetStatus {
		return &v
	}).(TrustedEntitySetStatusPtrOutput)
}

func (o TrustedEntitySetStatusOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o TrustedEntitySetStatusOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e TrustedEntitySetStatus) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o TrustedEntitySetStatusOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o TrustedEntitySetStatusOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e TrustedEntitySetStatus) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type TrustedEntitySetStatusPtrOutput struct{ *pulumi.OutputState }

func (TrustedEntitySetStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TrustedEntitySetStatus)(nil)).Elem()
}

func (o TrustedEntitySetStatusPtrOutput) ToTrustedEntitySetStatusPtrOutput() TrustedEntitySetStatusPtrOutput {
	return o
}

func (o TrustedEntitySetStatusPtrOutput) ToTrustedEntitySetStatusPtrOutputWithContext(ctx context.Context) TrustedEntitySetStatusPtrOutput {
	return o
}

func (o TrustedEntitySetStatusPtrOutput) Elem() TrustedEntitySetStatusOutput {
	return o.ApplyT(func(v *TrustedEntitySetStatus) TrustedEntitySetStatus {
		if v != nil {
			return *v
		}
		var ret TrustedEntitySetStatus
		return ret
	}).(TrustedEntitySetStatusOutput)
}

func (o TrustedEntitySetStatusPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o TrustedEntitySetStatusPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *TrustedEntitySetStatus) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CustomDetectionRuleAssociationModeInput)(nil)).Elem(), CustomDetectionRuleAssociationMode("LIVE"))
	pulumi.RegisterInputType(reflect.TypeOf((*CustomDetectionRuleAssociationModePtrInput)(nil)).Elem(), CustomDetectionRuleAssociationMode("LIVE"))
	pulumi.RegisterInputType(reflect.TypeOf((*DetectorCfnFeatureConfigurationStatusInput)(nil)).Elem(), DetectorCfnFeatureConfigurationStatus("ENABLED"))
	pulumi.RegisterInputType(reflect.TypeOf((*DetectorCfnFeatureConfigurationStatusPtrInput)(nil)).Elem(), DetectorCfnFeatureConfigurationStatus("ENABLED"))
	pulumi.RegisterOutputType(CustomDetectionRuleAssociationModeOutput{})
	pulumi.RegisterOutputType(CustomDetectionRuleAssociationModePtrOutput{})
	pulumi.RegisterOutputType(DetectorCfnFeatureConfigurationStatusOutput{})
	pulumi.RegisterOutputType(DetectorCfnFeatureConfigurationStatusPtrOutput{})
	pulumi.RegisterOutputType(ThreatEntitySetStatusOutput{})
	pulumi.RegisterOutputType(ThreatEntitySetStatusPtrOutput{})
	pulumi.RegisterOutputType(TrustedEntitySetStatusOutput{})
	pulumi.RegisterOutputType(TrustedEntitySetStatusPtrOutput{})
}
