// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Eks.Inputs
{

    /// <summary>
    /// A mapping between an Argo CD role and IAM Identity Center identities. This defines which users or groups have specific permissions in Argo CD.
    /// </summary>
    public sealed class CapabilityArgoCdRoleMappingArgs : global::Pulumi.ResourceArgs
    {
        [Input("identities", required: true)]
        private InputList<Inputs.CapabilitySsoIdentityArgs>? _identities;

        /// <summary>
        /// A list of IAM Identity Center identities (users or groups) that should be assigned this Argo CD role.
        /// </summary>
        public InputList<Inputs.CapabilitySsoIdentityArgs> Identities
        {
            get => _identities ?? (_identities = new InputList<Inputs.CapabilitySsoIdentityArgs>());
            set => _identities = value;
        }

        /// <summary>
        /// The Argo CD role to assign. Valid values are: ADMIN (full administrative access to Argo CD), EDITOR (edit access to Argo CD resources), or VIEWER (read-only access to Argo CD resources).
        /// </summary>
        [Input("role", required: true)]
        public Input<Pulumi.AwsNative.Eks.CapabilityArgoCdRoleMappingRole> Role { get; set; } = null!;

        public CapabilityArgoCdRoleMappingArgs()
        {
        }
        public static new CapabilityArgoCdRoleMappingArgs Empty => new CapabilityArgoCdRoleMappingArgs();
    }
}
