// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.NetworkManager.Inputs
{

    /// <summary>
    /// The attachment to move from one segment to another.
    /// </summary>
    public sealed class DirectConnectGatewayAttachmentProposedSegmentChangeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The rule number in the policy document that applies to this change.
        /// </summary>
        [Input("attachmentPolicyRuleNumber")]
        public Input<int>? AttachmentPolicyRuleNumber { get; set; }

        /// <summary>
        /// The name of the segment to change.
        /// </summary>
        [Input("segmentName")]
        public Input<string>? SegmentName { get; set; }

        [Input("tags")]
        private InputList<Inputs.DirectConnectGatewayAttachmentTagArgs>? _tags;

        /// <summary>
        /// The key-value tags that changed for the segment.
        /// </summary>
        public InputList<Inputs.DirectConnectGatewayAttachmentTagArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.DirectConnectGatewayAttachmentTagArgs>());
            set => _tags = value;
        }

        public DirectConnectGatewayAttachmentProposedSegmentChangeArgs()
        {
        }
        public static new DirectConnectGatewayAttachmentProposedSegmentChangeArgs Empty => new DirectConnectGatewayAttachmentProposedSegmentChangeArgs();
    }
}
