// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Bedrock.Outputs
{

    [OutputType]
    public sealed class DataAutomationProjectAudioOverrideConfiguration
    {
        /// <summary>
        /// Sets modality processing for audio files. All modalities are enabled by default.
        /// </summary>
        public readonly Outputs.DataAutomationProjectModalityProcessingConfiguration? ModalityProcessing;

        [OutputConstructor]
        private DataAutomationProjectAudioOverrideConfiguration(Outputs.DataAutomationProjectModalityProcessingConfiguration? modalityProcessing)
        {
            ModalityProcessing = modalityProcessing;
        }
    }
}
