// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Bedrock.Outputs
{

    /// <summary>
    /// Inline prompt configuration for prompt node
    /// </summary>
    [OutputType]
    public sealed class FlowVersionPromptFlowNodeInlineConfiguration
    {
        public readonly Outputs.FlowVersionPromptInferenceConfigurationProperties? InferenceConfiguration;
        /// <summary>
        /// ARN or Id of a Bedrock Foundational Model or Inference Profile, or the ARN of a imported model, or a provisioned throughput ARN for custom models.
        /// </summary>
        public readonly string ModelId;
        public readonly Outputs.FlowVersionPromptTemplateConfigurationProperties TemplateConfiguration;
        public readonly Pulumi.AwsNative.Bedrock.FlowVersionPromptTemplateType TemplateType;

        [OutputConstructor]
        private FlowVersionPromptFlowNodeInlineConfiguration(
            Outputs.FlowVersionPromptInferenceConfigurationProperties? inferenceConfiguration,

            string modelId,

            Outputs.FlowVersionPromptTemplateConfigurationProperties templateConfiguration,

            Pulumi.AwsNative.Bedrock.FlowVersionPromptTemplateType templateType)
        {
            InferenceConfiguration = inferenceConfiguration;
            ModelId = modelId;
            TemplateConfiguration = templateConfiguration;
            TemplateType = templateType;
        }
    }
}
