// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Transfer.Inputs
{

    /// <summary>
    /// Details for a step that creates one or more tags.
    /// </summary>
    public sealed class WorkflowStepTagStepDetailsPropertiesArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the step, used as an identifier.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<Inputs.WorkflowS3TagArgs>? _tags;

        /// <summary>
        /// Array that contains from 1 to 10 key/value pairs.
        /// </summary>
        public InputList<Inputs.WorkflowS3TagArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.WorkflowS3TagArgs>());
            set => _tags = value;
        }

        public WorkflowStepTagStepDetailsPropertiesArgs()
        {
        }
    }
}
