// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.DynamoDb.Outputs
{

    /// <summary>
    /// Represents an attribute for describing the schema for the table and indexes.
    /// </summary>
    [OutputType]
    public sealed class TableAttributeDefinition
    {
        /// <summary>
        /// A name for the attribute.
        /// </summary>
        public readonly string AttributeName;
        /// <summary>
        /// The data type for the attribute, where:
        ///   +   ``S`` - the attribute is of type String
        ///   +   ``N`` - the attribute is of type Number
        ///   +   ``B`` - the attribute is of type Binary
        /// </summary>
        public readonly string AttributeType;

        [OutputConstructor]
        private TableAttributeDefinition(
            string attributeName,

            string attributeType)
        {
            AttributeName = attributeName;
            AttributeType = attributeType;
        }
    }
}
