# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = ['AccountCustomizationArgs', 'AccountCustomization']

@pulumi.input_type
class AccountCustomizationArgs:
    def __init__(__self__, *,
                 account_color: pulumi.Input[Optional['AccountCustomizationAccountColor']] = None,
                 visible_regions: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 visible_services: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a AccountCustomization resource.

        :param pulumi.Input['AccountCustomizationAccountColor'] account_color: The color theme assigned to the account for visual identification in the AWS Console.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] visible_regions: A list of AWS region identifiers visible to the account in the AWS Console.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] visible_services: A list of AWS service identifiers visible to the account in the AWS Console.
        """
        if account_color is not None:
            pulumi.set(__self__, "account_color", account_color)
        if visible_regions is not None:
            pulumi.set(__self__, "visible_regions", visible_regions)
        if visible_services is not None:
            pulumi.set(__self__, "visible_services", visible_services)

    @_builtins.property
    @pulumi.getter(name="accountColor")
    def account_color(self) -> pulumi.Input[Optional['AccountCustomizationAccountColor']]:
        """
        The color theme assigned to the account for visual identification in the AWS Console.
        """
        return pulumi.get(self, "account_color")

    @account_color.setter
    def account_color(self, value: pulumi.Input[Optional['AccountCustomizationAccountColor']]):
        pulumi.set(self, "account_color", value)

    @_builtins.property
    @pulumi.getter(name="visibleRegions")
    def visible_regions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of AWS region identifiers visible to the account in the AWS Console.
        """
        return pulumi.get(self, "visible_regions")

    @visible_regions.setter
    def visible_regions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "visible_regions", value)

    @_builtins.property
    @pulumi.getter(name="visibleServices")
    def visible_services(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of AWS service identifiers visible to the account in the AWS Console.
        """
        return pulumi.get(self, "visible_services")

    @visible_services.setter
    def visible_services(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "visible_services", value)


@pulumi.type_token("aws-native:uxc:AccountCustomization")
class AccountCustomization(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_color: pulumi.Input[Optional['AccountCustomizationAccountColor']] = None,
                 visible_regions: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 visible_services: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Resource schema for managing AWS account-level UX customization settings, including account color, visible services, and visible regions.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input['AccountCustomizationAccountColor'] account_color: The color theme assigned to the account for visual identification in the AWS Console.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] visible_regions: A list of AWS region identifiers visible to the account in the AWS Console.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] visible_services: A list of AWS service identifiers visible to the account in the AWS Console.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[AccountCustomizationArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Resource schema for managing AWS account-level UX customization settings, including account color, visible services, and visible regions.

        :param str resource_name: The name of the resource.
        :param AccountCustomizationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AccountCustomizationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_color: pulumi.Input[Optional['AccountCustomizationAccountColor']] = None,
                 visible_regions: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 visible_services: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AccountCustomizationArgs.__new__(AccountCustomizationArgs)

            __props__.__dict__["account_color"] = account_color
            __props__.__dict__["visible_regions"] = visible_regions
            __props__.__dict__["visible_services"] = visible_services
            __props__.__dict__["account_id"] = None
        super(AccountCustomization, __self__).__init__(
            'aws-native:uxc:AccountCustomization',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'AccountCustomization':
        """
        Get an existing AccountCustomization resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = AccountCustomizationArgs.__new__(AccountCustomizationArgs)

        __props__.__dict__["account_color"] = None
        __props__.__dict__["account_id"] = None
        __props__.__dict__["visible_regions"] = None
        __props__.__dict__["visible_services"] = None
        return AccountCustomization(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountColor")
    def account_color(self) -> pulumi.Output[Optional['AccountCustomizationAccountColor']]:
        """
        The color theme assigned to the account for visual identification in the AWS Console.
        """
        return pulumi.get(self, "account_color")

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[_builtins.str]:
        """
        The AWS account ID that this customization belongs to. This is automatically determined from the caller's identity.
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="visibleRegions")
    def visible_regions(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A list of AWS region identifiers visible to the account in the AWS Console.
        """
        return pulumi.get(self, "visible_regions")

    @_builtins.property
    @pulumi.getter(name="visibleServices")
    def visible_services(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A list of AWS service identifiers visible to the account in the AWS Console.
        """
        return pulumi.get(self, "visible_services")

