// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.CleanRooms.Outputs
{

    [OutputType]
    public sealed class ConfiguredTableAggregationThreshold
    {
        public readonly Pulumi.AwsNative.CleanRooms.ConfiguredTableAllowedAggregateExpressionType AllowedAggregateExpressionType;
        public readonly ImmutableArray<string> IdentityColumns;
        public readonly int MinimumIdentityCount;
        public readonly ImmutableArray<Outputs.ConfiguredTableOutputColumnThreshold> OutputColumnThresholds;
        public readonly Pulumi.AwsNative.CleanRooms.ConfiguredTableAggregationThresholdType Type;

        [OutputConstructor]
        private ConfiguredTableAggregationThreshold(
            Pulumi.AwsNative.CleanRooms.ConfiguredTableAllowedAggregateExpressionType allowedAggregateExpressionType,

            ImmutableArray<string> identityColumns,

            int minimumIdentityCount,

            ImmutableArray<Outputs.ConfiguredTableOutputColumnThreshold> outputColumnThresholds,

            Pulumi.AwsNative.CleanRooms.ConfiguredTableAggregationThresholdType type)
        {
            AllowedAggregateExpressionType = allowedAggregateExpressionType;
            IdentityColumns = identityColumns;
            MinimumIdentityCount = minimumIdentityCount;
            OutputColumnThresholds = outputColumnThresholds;
            Type = type;
        }
    }
}
