# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'GetPermissionAssociationResult',
    'AwaitableGetPermissionAssociationResult',
    'get_permission_association',
    'get_permission_association_output',
]

@pulumi.output_type
class GetPermissionAssociationResult:
    def __init__(__self__, association_status=None, feature_set=None, is_default=None, last_updated_time=None, permission_version=None, resource_type=None):
        if association_status and not isinstance(association_status, str):
            raise TypeError("Expected argument 'association_status' to be a str")
        pulumi.set(__self__, "association_status", association_status)
        if feature_set and not isinstance(feature_set, str):
            raise TypeError("Expected argument 'feature_set' to be a str")
        pulumi.set(__self__, "feature_set", feature_set)
        if is_default and not isinstance(is_default, bool):
            raise TypeError("Expected argument 'is_default' to be a bool")
        pulumi.set(__self__, "is_default", is_default)
        if last_updated_time and not isinstance(last_updated_time, str):
            raise TypeError("Expected argument 'last_updated_time' to be a str")
        pulumi.set(__self__, "last_updated_time", last_updated_time)
        if permission_version and not isinstance(permission_version, str):
            raise TypeError("Expected argument 'permission_version' to be a str")
        pulumi.set(__self__, "permission_version", permission_version)
        if resource_type and not isinstance(resource_type, str):
            raise TypeError("Expected argument 'resource_type' to be a str")
        pulumi.set(__self__, "resource_type", resource_type)

    @_builtins.property
    @pulumi.getter(name="associationStatus")
    def association_status(self) -> Optional['PermissionAssociationAssociationStatus']:
        """
        The current status of the association between the permission and the resource share.
        """
        return pulumi.get(self, "association_status")

    @_builtins.property
    @pulumi.getter(name="featureSet")
    def feature_set(self) -> Optional['PermissionAssociationFeatureSet']:
        """
        The feature set of the resource share.
        """
        return pulumi.get(self, "feature_set")

    @_builtins.property
    @pulumi.getter(name="isDefault")
    def is_default(self) -> Optional[_builtins.bool]:
        """
        Indicates whether the associated resource share is using the default version of the permission.
        """
        return pulumi.get(self, "is_default")

    @_builtins.property
    @pulumi.getter(name="lastUpdatedTime")
    def last_updated_time(self) -> Optional[_builtins.str]:
        """
        The date and time when the association between the permission and the resource share was last updated.
        """
        return pulumi.get(self, "last_updated_time")

    @_builtins.property
    @pulumi.getter(name="permissionVersion")
    def permission_version(self) -> Optional[_builtins.str]:
        """
        The version of the permission currently associated with the resource share.
        """
        return pulumi.get(self, "permission_version")

    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> Optional[_builtins.str]:
        """
        The resource type to which the permission applies.
        """
        return pulumi.get(self, "resource_type")


class AwaitableGetPermissionAssociationResult(GetPermissionAssociationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPermissionAssociationResult(
            association_status=self.association_status,
            feature_set=self.feature_set,
            is_default=self.is_default,
            last_updated_time=self.last_updated_time,
            permission_version=self.permission_version,
            resource_type=self.resource_type)


def get_permission_association(permission_arn: Optional[_builtins.str] = None,
                               resource_share_arn: Optional[_builtins.str] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPermissionAssociationResult:
    """
    Associates a specified AWS RAM permission with a resource share. You can only associate one permission with each resource type in a resource share.

    :param _builtins.str permission_arn: Specifies the [Amazon Resource Name (ARN)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) of the AWS RAM permission to associate with the resource share.
    :param _builtins.str resource_share_arn: Specifies the [Amazon Resource Name (ARN)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) of the resource share.
    """
    __args__ = dict()
    __args__['permissionArn'] = permission_arn
    __args__['resourceShareArn'] = resource_share_arn
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('aws-native:ram:getPermissionAssociation', __args__, opts=opts, typ=GetPermissionAssociationResult).value

    return AwaitableGetPermissionAssociationResult(
        association_status=pulumi.get(__ret__, 'association_status'),
        feature_set=pulumi.get(__ret__, 'feature_set'),
        is_default=pulumi.get(__ret__, 'is_default'),
        last_updated_time=pulumi.get(__ret__, 'last_updated_time'),
        permission_version=pulumi.get(__ret__, 'permission_version'),
        resource_type=pulumi.get(__ret__, 'resource_type'))
def get_permission_association_output(permission_arn: pulumi.Input[Optional[_builtins.str]] = None,
                                      resource_share_arn: pulumi.Input[Optional[_builtins.str]] = None,
                                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPermissionAssociationResult]:
    """
    Associates a specified AWS RAM permission with a resource share. You can only associate one permission with each resource type in a resource share.

    :param _builtins.str permission_arn: Specifies the [Amazon Resource Name (ARN)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) of the AWS RAM permission to associate with the resource share.
    :param _builtins.str resource_share_arn: Specifies the [Amazon Resource Name (ARN)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) of the resource share.
    """
    __args__ = dict()
    __args__['permissionArn'] = permission_arn
    __args__['resourceShareArn'] = resource_share_arn
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('aws-native:ram:getPermissionAssociation', __args__, opts=opts, typ=GetPermissionAssociationResult)
    return __ret__.apply(lambda __response__: GetPermissionAssociationResult(
        association_status=pulumi.get(__response__, 'association_status'),
        feature_set=pulumi.get(__response__, 'feature_set'),
        is_default=pulumi.get(__response__, 'is_default'),
        last_updated_time=pulumi.get(__response__, 'last_updated_time'),
        permission_version=pulumi.get(__response__, 'permission_version'),
        resource_type=pulumi.get(__response__, 'resource_type')))
