// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.VpcLattice.Outputs
{

    [OutputType]
    public sealed class ListenerDefaultAction
    {
        /// <summary>
        /// Describes an action that returns a custom HTTP response.
        /// </summary>
        public readonly Outputs.ListenerFixedResponse? FixedResponse;
        /// <summary>
        /// The forward action. Traffic that matches the rule is forwarded to the specified target groups.
        /// </summary>
        public readonly Outputs.ListenerForward? Forward;

        [OutputConstructor]
        private ListenerDefaultAction(
            Outputs.ListenerFixedResponse? fixedResponse,

            Outputs.ListenerForward? forward)
        {
            FixedResponse = fixedResponse;
            Forward = forward;
        }
    }
}
