// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.IoT.Outputs
{

    /// <summary>
    /// A structure containing the configName and corresponding configValue for configuring audit checks.
    /// </summary>
    [OutputType]
    public sealed class AccountAuditConfigurationCertAgeCheckCustomConfiguration
    {
        public readonly string? CertAgeThresholdInDays;

        [OutputConstructor]
        private AccountAuditConfigurationCertAgeCheckCustomConfiguration(string? certAgeThresholdInDays)
        {
            CertAgeThresholdInDays = certAgeThresholdInDays;
        }
    }
}
