// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package iot

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-aws-native/sdk/go/aws"
	"github.com/pulumi/pulumi-aws-native/sdk/go/aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use the AWS::IoT::CertificateProvider resource to declare an AWS IoT Certificate Provider.
type CertificateProvider struct {
	pulumi.CustomResourceState

	// A list of the operations that the certificate provider will use to generate certificates. Valid value: `CreateCertificateFromCsr` .
	AccountDefaultForOperations CertificateProviderOperationArrayOutput `pulumi:"accountDefaultForOperations"`
	// Returns the Amazon Resource Name (ARN) for the certificate. For example:
	//
	// `{ "Fn::GetAtt": ["MyCertificateProvider", "Arn"] }`
	//
	// A value similar to the following is returned:
	//
	// `arn:aws:iot:ap-southeast-2:123456789012:certprovider/my-certificate-provider`
	Arn pulumi.StringOutput `pulumi:"arn"`
	// The name of the certificate provider.
	CertificateProviderName pulumi.StringPtrOutput `pulumi:"certificateProviderName"`
	// The ARN of the Lambda function.
	LambdaFunctionArn pulumi.StringOutput `pulumi:"lambdaFunctionArn"`
	// An array of key-value pairs to apply to this resource.
	Tags aws.TagArrayOutput `pulumi:"tags"`
}

// NewCertificateProvider registers a new resource with the given unique name, arguments, and options.
func NewCertificateProvider(ctx *pulumi.Context,
	name string, args *CertificateProviderArgs, opts ...pulumi.ResourceOption) (*CertificateProvider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountDefaultForOperations == nil {
		return nil, errors.New("invalid value for required argument 'AccountDefaultForOperations'")
	}
	if args.LambdaFunctionArn == nil {
		return nil, errors.New("invalid value for required argument 'LambdaFunctionArn'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"certificateProviderName",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CertificateProvider
	err := ctx.RegisterResource("aws-native:iot:CertificateProvider", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCertificateProvider gets an existing CertificateProvider resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCertificateProvider(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CertificateProviderState, opts ...pulumi.ResourceOption) (*CertificateProvider, error) {
	var resource CertificateProvider
	err := ctx.ReadResource("aws-native:iot:CertificateProvider", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CertificateProvider resources.
type certificateProviderState struct {
}

type CertificateProviderState struct {
}

func (CertificateProviderState) ElementType() reflect.Type {
	return reflect.TypeOf((*certificateProviderState)(nil)).Elem()
}

type certificateProviderArgs struct {
	// A list of the operations that the certificate provider will use to generate certificates. Valid value: `CreateCertificateFromCsr` .
	AccountDefaultForOperations []CertificateProviderOperation `pulumi:"accountDefaultForOperations"`
	// The name of the certificate provider.
	CertificateProviderName *string `pulumi:"certificateProviderName"`
	// The ARN of the Lambda function.
	LambdaFunctionArn string `pulumi:"lambdaFunctionArn"`
	// An array of key-value pairs to apply to this resource.
	Tags []aws.Tag `pulumi:"tags"`
}

// The set of arguments for constructing a CertificateProvider resource.
type CertificateProviderArgs struct {
	// A list of the operations that the certificate provider will use to generate certificates. Valid value: `CreateCertificateFromCsr` .
	AccountDefaultForOperations CertificateProviderOperationArrayInput
	// The name of the certificate provider.
	CertificateProviderName pulumi.StringPtrInput
	// The ARN of the Lambda function.
	LambdaFunctionArn pulumi.StringInput
	// An array of key-value pairs to apply to this resource.
	Tags aws.TagArrayInput
}

func (CertificateProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*certificateProviderArgs)(nil)).Elem()
}

type CertificateProviderInput interface {
	pulumi.Input

	ToCertificateProviderOutput() CertificateProviderOutput
	ToCertificateProviderOutputWithContext(ctx context.Context) CertificateProviderOutput
}

func (*CertificateProvider) ElementType() reflect.Type {
	return reflect.TypeOf((**CertificateProvider)(nil)).Elem()
}

func (i *CertificateProvider) ToCertificateProviderOutput() CertificateProviderOutput {
	return i.ToCertificateProviderOutputWithContext(context.Background())
}

func (i *CertificateProvider) ToCertificateProviderOutputWithContext(ctx context.Context) CertificateProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CertificateProviderOutput)
}

type CertificateProviderOutput struct{ *pulumi.OutputState }

func (CertificateProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CertificateProvider)(nil)).Elem()
}

func (o CertificateProviderOutput) ToCertificateProviderOutput() CertificateProviderOutput {
	return o
}

func (o CertificateProviderOutput) ToCertificateProviderOutputWithContext(ctx context.Context) CertificateProviderOutput {
	return o
}

// A list of the operations that the certificate provider will use to generate certificates. Valid value: `CreateCertificateFromCsr` .
func (o CertificateProviderOutput) AccountDefaultForOperations() CertificateProviderOperationArrayOutput {
	return o.ApplyT(func(v *CertificateProvider) CertificateProviderOperationArrayOutput {
		return v.AccountDefaultForOperations
	}).(CertificateProviderOperationArrayOutput)
}

// Returns the Amazon Resource Name (ARN) for the certificate. For example:
//
// `{ "Fn::GetAtt": ["MyCertificateProvider", "Arn"] }`
//
// A value similar to the following is returned:
//
// `arn:aws:iot:ap-southeast-2:123456789012:certprovider/my-certificate-provider`
func (o CertificateProviderOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v *CertificateProvider) pulumi.StringOutput { return v.Arn }).(pulumi.StringOutput)
}

// The name of the certificate provider.
func (o CertificateProviderOutput) CertificateProviderName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CertificateProvider) pulumi.StringPtrOutput { return v.CertificateProviderName }).(pulumi.StringPtrOutput)
}

// The ARN of the Lambda function.
func (o CertificateProviderOutput) LambdaFunctionArn() pulumi.StringOutput {
	return o.ApplyT(func(v *CertificateProvider) pulumi.StringOutput { return v.LambdaFunctionArn }).(pulumi.StringOutput)
}

// An array of key-value pairs to apply to this resource.
func (o CertificateProviderOutput) Tags() aws.TagArrayOutput {
	return o.ApplyT(func(v *CertificateProvider) aws.TagArrayOutput { return v.Tags }).(aws.TagArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CertificateProviderInput)(nil)).Elem(), &CertificateProvider{})
	pulumi.RegisterOutputType(CertificateProviderOutput{})
}
