// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.QuickSight.Inputs
{

    public sealed class DashboardStaticFileArgs : global::Pulumi.ResourceArgs
    {
        [Input("imageStaticFile")]
        public Input<Inputs.DashboardImageStaticFileArgs>? ImageStaticFile { get; set; }

        [Input("spatialStaticFile")]
        public Input<Inputs.DashboardSpatialStaticFileArgs>? SpatialStaticFile { get; set; }

        public DashboardStaticFileArgs()
        {
        }
        public static new DashboardStaticFileArgs Empty => new DashboardStaticFileArgs();
    }
}
