// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.QuickSight.Inputs
{

    public sealed class DashboardDecimalParameterDeclarationArgs : global::Pulumi.ResourceArgs
    {
        [Input("defaultValues")]
        public Input<Inputs.DashboardDecimalDefaultValuesArgs>? DefaultValues { get; set; }

        [Input("mappedDataSetParameters")]
        private InputList<Inputs.DashboardMappedDataSetParameterArgs>? _mappedDataSetParameters;
        public InputList<Inputs.DashboardMappedDataSetParameterArgs> MappedDataSetParameters
        {
            get => _mappedDataSetParameters ?? (_mappedDataSetParameters = new InputList<Inputs.DashboardMappedDataSetParameterArgs>());
            set => _mappedDataSetParameters = value;
        }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("parameterValueType", required: true)]
        public Input<Pulumi.AwsNative.QuickSight.DashboardParameterValueType> ParameterValueType { get; set; } = null!;

        [Input("valueWhenUnset")]
        public Input<Inputs.DashboardDecimalValueWhenUnsetConfigurationArgs>? ValueWhenUnset { get; set; }

        public DashboardDecimalParameterDeclarationArgs()
        {
        }
        public static new DashboardDecimalParameterDeclarationArgs Empty => new DashboardDecimalParameterDeclarationArgs();
    }
}
