// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.QuickSight.Inputs
{

    public sealed class TemplateChartAxisLabelOptionsArgs : global::Pulumi.ResourceArgs
    {
        [Input("axisLabelOptions")]
        private InputList<Inputs.TemplateAxisLabelOptionsArgs>? _axisLabelOptions;
        public InputList<Inputs.TemplateAxisLabelOptionsArgs> AxisLabelOptions
        {
            get => _axisLabelOptions ?? (_axisLabelOptions = new InputList<Inputs.TemplateAxisLabelOptionsArgs>());
            set => _axisLabelOptions = value;
        }

        [Input("sortIconVisibility")]
        public Input<Pulumi.AwsNative.QuickSight.TemplateVisibility>? SortIconVisibility { get; set; }

        [Input("visibility")]
        public Input<Pulumi.AwsNative.QuickSight.TemplateVisibility>? Visibility { get; set; }

        public TemplateChartAxisLabelOptionsArgs()
        {
        }
        public static new TemplateChartAxisLabelOptionsArgs Empty => new TemplateChartAxisLabelOptionsArgs();
    }
}
