// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsNative.Cognito.Outputs
{

    [OutputType]
    public sealed class UserPoolPolicies
    {
        /// <summary>
        /// The password policy settings for a user pool, including complexity, history, and length requirements.
        /// </summary>
        public readonly Outputs.UserPoolPasswordPolicy? PasswordPolicy;
        /// <summary>
        /// The policy for allowed types of authentication in a user pool. To activate this setting, your user pool must be in the [Essentials tier](https://docs.aws.amazon.com/cognito/latest/developerguide/feature-plans-features-essentials.html) or higher.
        /// </summary>
        public readonly Outputs.UserPoolSignInPolicy? SignInPolicy;

        [OutputConstructor]
        private UserPoolPolicies(
            Outputs.UserPoolPasswordPolicy? passwordPolicy,

            Outputs.UserPoolSignInPolicy? signInPolicy)
        {
            PasswordPolicy = passwordPolicy;
            SignInPolicy = signInPolicy;
        }
    }
}
